version: "3.9"

services:
  availablityio:
    container_name: availablityio
    image: hossman39/Availablitio:latest
    ports:
      - "7874:7874"
    environment:
      - TMDB_API_KEY=${TMDB_API_KEY}
      - PORT=7874
